name: Beiroes CI/CD

on:
  push:
    branches: [ main , dev ]

jobs:
  deploy:
    runs-on: self-hosted # Your Raspberry Pi
    steps:
      - name: Sync Code
        run: git pull origin main

      - name: Install Dependencies
        run: pip install --upgrade pip && pip install -r backend/requirements.txt

      - name: Run Internal Tests
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_USER: beiroes_admin
          DB_PASSWORD: ${DB_PASSWORD}
          DB_NAME: beiroes_test
          PYTHONPATH: ${{ github.workspace }}/backend/app
        run: |
          cd backend/app
          python3 auto_test_all.py

      - name: Docker Deployment
        run: docker-compose --env-file .env up -d --build