name: Beiroes CI/CD

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make deploy script executable
        run: chmod +x local_deploy.sh

      - name: Run deployment
        run: ./local_deploy.sh